14 lastfm locale/audio/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, ListView

from audio.views import *

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^tracks$', show_all, name='tracks'),
    # url(r'^tracks$', ListView.as_view(
    #                 context_object_name='audios',
    #                 model=Audio,
    #                 paginate_by=5,
    #                 template_name='audio/all_audio.html'),
    #     name='tracks'),
    url(r'^tracks/(?P<audio_id>\d+)$', audio_page, name='audio_page'),
    url(r'^tracks/(?P<audio_id>\d+)/data$', audio_data_page, name='audio_data_page'),
    url(r'^tracks/new$', add_audio, name='add_audio'),
    url(r'^tracks/(?P<audio_id>\d+)/update', AudioFormView.as_view(), name='update_audio'),
    url(r'^ads/$', AdsView.as_view(), name='ads')
]

14 lastfm locale/lastfm/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from lastfm import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^audio/', include('audio.urls', namespace="audio")),
    url(r'^gallery/', include('gallery.urls', namespace="gallery")),
    url(r'^login/', 'audio.views.login', name="login"),
    url(r'^logout/', 'audio.views.logout', name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

14 lastfm locale/audio/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User

genres = (
        ("rock", "Rock"),
        ("hm", "Heavy Metal"),
        ("pop", "Pop music"),
        ("pth", "Patriotic Trance House"),
)


class Audio(models.Model):
    class Meta:
        db_table = "audios"
        verbose_name_plural = u'Аудиозаписи'
        unique_together = ['title', 'artist']

    title = models.CharField(max_length=50)
    artist = models.ForeignKey('Artist', related_name="audios", null=True)

    album = models.CharField(max_length=50, blank=True)
    anon_likes = models.IntegerField(default=0)
    genre = models.CharField(max_length=4, choices=genres, null=True)
    favorite = models.ManyToManyField(User, related_name="favorites")


    def __unicode__(self):
        return "%s : %s : %s - %s likes" % (self.artist, self.title, 
            self.album, self.anon_likes)

class AudioData(models.Model):
    audio = models.ForeignKey("Audio")
    year = models.PositiveSmallIntegerField(null=True)
    bitrate = models.PositiveSmallIntegerField(null=True)
    duration = models.IntegerField()
    phone_of_author = models.CharField(blank=True, max_length=20)
    description = models.TextField(blank=True)

    def __unicode__(self):
        return "%s:%s:%s" % (self.audio, self.duration, self.year)


def get_artist_image_path(instance, filename):
    return instance.name + filename

class Artist(models.Model):
    class Meta:
        db_table = "artists"

    name = models.CharField(max_length=50, unique=True)
    country = models.CharField(max_length=30, blank=True)
    image = models.ImageField(null=True, upload_to=get_artist_image_path)

    def __unicode__(self):
        return self.name


class Duet(Audio):
    artist2 = models.ForeignKey('Artist', related_name='audios_from_duet', null=True)

14 lastfm locale/audio/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from audio.models import Audio

def validate_year_XX(value):
    if value < 1900:
        raise ValidationError(u'To old for our cool modern awesome uber super app!')

class AudioForm(forms.ModelForm):
    class Meta:
        model = Audio
        fields = ["title", "artist", "genre"]

class AudioDataForm(forms.Form):
    bitrate = forms.IntegerField()
    year = forms.IntegerField(validators=[validate_year_XX])
    duration = forms.IntegerField()
    phone_of_author = forms.CharField(
        validators=[RegexValidator(r'\+\d{,3}-\(\d{3}\)-\d{3}-\d{2}-\d{2}', "Wrong number format!")]
    )
    description = forms.CharField(widget=forms.Textarea)

14 lastfm locale/audio/views.py
import json
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect as redirect
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, UpdateView
from django.utils.translation import ugettext as _
from audio.forms import AudioForm, AudioDataForm
from audio.models import Audio, Artist, genres, AudioData


def login(request):
    # authenticated user does not need to log in
    if request.user.is_authenticated():
        return redirect(reverse("audio:index"))

    if request.method == "GET":
        context = {}
        if "next" in request.GET:
            context["next"] = "?next=" + request.GET["next"]
        return render(request, "audio/login.html", context)

    elif request.method == "POST":
        user = authenticate(
            username=request.POST["username"],
            password=request.POST["password"]
        )
        if user is not None:
            auth_login(request, user)
            if "next" in request.GET:
                return redirect(request.GET["next"])
            else:
                return redirect(reverse("audio:index"))
        else:
            return redirect(reverse("login"))
    else:
        return HttpResponse("405")


@login_required(login_url=reverse_lazy("login"))
def index(request):
    audios = request.user.favorites.all()

    return render(request, "audio/index.html",
                  {"username": request.user.username,
                   "audios": audios})


@login_required(login_url=reverse_lazy("login"))
def show_all(request):
    s = _("All tracks") + "!<br/><a href=\"%s\">Back to Index</a><br><br>" % reverse("audio:index")

    # artist = Artist.objects.get(name="AC/DC")
    # audios = Audio.objects.filter(artist=artist)
    audios = Audio.objects.all()
    s += "".join(map(lambda x: "<li>%s</li>" % x, audios))

    return HttpResponse(s)


def logout(request):
    auth_logout(request)
    return redirect(reverse("login"))


@login_required(login_url=reverse_lazy("login"))
def audio_page(request, audio_id):
    audio_object = Audio.objects.get(id=audio_id)
    who_favorited = audio_object.favorite.all()
    return render(request, "audio/audio_page.html", {"audio": audio_object,
                                                     "liked": who_favorited})


@login_required(login_url=reverse_lazy("login"))
def add_audio_old(request):
    if request.method == "GET":
        return render(request, "audio/add_audio.html", {
            "artists": Artist.objects.values("id", "name"),
            "genres": genres
        })

    elif request.method == "POST":
        a = Audio()
        a.title = request.POST["title"]
        a.artist_id = request.POST["artist"]
        a.genre = request.POST["genre"]
        a.save()
        return redirect(reverse("audio:audio_page", args=(a.id,)))
    else:
        return HttpResponse("405")


@login_required(login_url=reverse_lazy("login"))
def add_audio(request):
    if request.method == "GET":
        f = AudioForm()
        return render(request, "audio/add_audio.html", {"f": f})

    elif request.method == "POST":
        f = AudioForm(request.POST)
        if f.is_valid():
            a = f.save()
            return redirect(reverse("audio:audio_page", args=(a.id,)))
    else:
        return HttpResponse("405")

class AudioFormView(UpdateView):
    form_class = AudioForm
    template_name = "audio/change_audio.html"
    model = Audio
    success_url = reverse_lazy("audio:index")

    def get_object(self, queryset=None):
        return Audio.objects.get(id=self.kwargs["audio_id"])

    def get_success_url(self):
        return reverse("audio:audio_page", args=(self.kwargs["audio_id"],))


def audio_data_page(request, audio_id):
    if request.method == "GET":
        ad = AudioData.objects.filter(audio_id=audio_id)
        if ad.exists():
            s = serializers.serialize("json", ad)
            data = json.loads(s)
            data = data[0]["fields"]
            f = AudioDataForm(initial=data)
        else:
            f = AudioDataForm()
        return render(request, "audio/audio_data_page.html", {"f": f})
    elif request.method == "POST":
        f = AudioDataForm(request.POST)
        if f.is_valid():

            result_ad = AudioData.objects.filter(audio_id=audio_id)
            if result_ad.exists():
                ad = result_ad[0]
            else:
                ad = AudioData(audio_id=audio_id)

            ad.bitrate = f.cleaned_data["bitrate"]
            ad.year = f.cleaned_data["year"]
            ad.phone_of_author = f.cleaned_data["phone_of_author"]
            ad.description = f.cleaned_data["description"]
            ad.duration = f.cleaned_data["duration"]
            ad.save()
            return redirect(reverse("audio:audio_data_page", args=(audio_id,)))
        else:
            return render(request, "audio/audio_data_page.html", {"f": f})
    else:
        return HttpResponse("405")

class AdsView(TemplateView):
    template_name = 'audio/ads.html'

    def get_context_data(self, **kwargs):

        context = super(AdsView, self).get_context_data(**kwargs)

        #context["number_of_audio"] = Audio.objects.raw(
        #    "select id, count(*) as number_of_audios from audios")[0].number_of_audios

        context["number_of_audio"] = Audio.objects.count()
        return context

14 lastfm locale/audio/templates/audio/add_audio.html
{% extends "base.html" %}

{% block content %}

    <form action="{% url "audio:add_audio" %}" method="POST">{% csrf_token %}

        {{ f.as_p }}

        <input type="submit" value="save"/>

    </form>

{% endblock %}

14 lastfm locale/audio/templates/audio/add_audio_old.html
{% extends "base.html" %}

{% block content %}

    <form action="{% url "audio:add_audio" %}" method="POST">{% csrf_token %}

        <p><input type="text" name="title" placeholder="title"/></p>

        <p><select name="artist">
            {% for artist in artists %}
                <option value="{{ artist.id }}">{{ artist.name }}</option>
            {% endfor %}
        </select></p>

        <p><select name="genre">
            {% for genre in genres %}
                <option value="{{ genre.0 }}">{{ genre.1 }}</option>
            {% endfor %}
        </select></p>

        <input type="submit" value="save"/>

    </form>

{% endblock %}

14 lastfm locale/audio/templates/audio/ads.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

<h1>ADS</h1>
ITIS is the best!
<p>And we have {{ number_of_audio }} tracks.</p>

</body>
</html>

14 lastfm locale/audio/templates/audio/all_audio.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<ul>
    {% for audio in audios %}
        <li>{{ audio }}</li>
    {% endfor %}
</ul>

</body>
</html>

14 lastfm locale/audio/templates/audio/audio_data_page.html
{% extends "base.html" %}

{% block content %}
    <form method="post">{% csrf_token %}

        {{ f.as_p }}
        <input type="submit" value="Save"/>

    </form>



{% endblock %}

14 lastfm locale/audio/templates/audio/audio_page.html
{% extends "base.html" %}

{% block content %}
    <p>Track</p>
    <h2>{{ audio.title }}</h2>
    <p><i>Artist</i>: {{ audio.artist }}</p>
    <p><i>Album</i>: {{ audio.album }}</p>
    <p><i>Genre</i>: {{ audio.get_genre_display }}</p>
    Favorited by:
    <ul>
        {% for u in liked %}
            <li>{{ u.username }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'audio:audio_data_page' audio.id %}">Audio Data</a> |
    <a href="{% url 'audio:update_audio' audio.id %}">Update Info</a> |
{% endblock %}

14 lastfm locale/audio/templates/audio/change_audio.html
{% extends "base.html" %}

{% block content %}

    <form method="POST">{% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="save"/>

    </form>

{% endblock %}

14 lastfm locale/audio/templates/audio/edit_audio.html
{% extends "base.html" %}

{% block content %}

    <form method="POST">{% csrf_token %}

        {{ f.as_p }}

        <input type="submit" value="save"/>

    </form>

{% endblock %}

14 lastfm locale/audio/templates/audio/index.html
{% extends "base.html" %}

{% block content %}

<h3>Hello, {{ username }}!</h3>
<a href="{% url "audio:tracks" %}">All audios</a> |
<a href="{% url "audio:add_audio" %}">Add new</a> |
<a href="{% url "logout" %}">Log out</a>

<h4>Favorite music:</h4>
{% if audios %}

    {% for audio in audios %}
        <li><a href="{% url "audio:audio_page" audio.id %}">
            {{ audio.title }} ({{ audio.artist }})
        </a></li>
    {% endfor %}

{% else %}

    You did not add any songs to your list. Do it now!

{% endif %}

{% endblock %}

14 lastfm locale/audio/templates/audio/login.html
{% extends "base.html" %}

{% block content %}

<form action="{% url "login" %}{{ next }}" method="POST">

    {% csrf_token %}

    <p><input type="text" name="username" placeholder="username" /></p>

    <p><input type="password" name="password" placeholder="password" /></p>

    <p><input type="submit" value="Login" /> </p>

</form>

{% endblock %}